export const data=[
    {
    "id": "1",
    "head1": "EXCLUDES HAIR WASH",
    "head2": "30 Minute Express Trim",
    "price": 549,
    "time": "35 mins",
    "des1": "A quick trim to remove split ends while minimally reducing hair length",
    "desc2": "Blowdry not included",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1650711648402-3502ab.jpeg",
    "qty": 1
    },
    {
    "id": "2",
    "head1": "FOR 6-15 YEAR GIRLS",
    "head2": "Girl's Haircut",
    "price": 649,
    "time": "45 mins",
    "des1": "Choose from a range of haircuts like layers, bangs, bobs, etc.",
    "desc2": "Complimentary blowdry to complete the look",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1644151475715-26a85e.jpeg",
    "qty": 1
    },
    {
    "id": "3",
    "head1": "FOR 6-15 YEAR GIRLS",
    "head2": "Mom and Daughter Pack",
    "price": 1049,
    "time": "1 hr 30 mins",
    "des1": "Choose from a range of haircuts like layers, bangs, bobs, etc.",
    "desc2": "Complimentary blowdry to complete the look",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1637643281048-3b4e78.png",
    "qty": 1
    },
    {
    "id": "4",
    "head1": "Blowdry and Styling",
    "head2": "Blowdry: Straight & Smooth",
    "price": 399,
    "time": "30 mins",
    "des1": "Simple blowdry to give you smooth and straight hair for a few hours",
    "desc2": "For a frizz-free, longer lasting look, please choose straightening",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1651666584674-3b0b6c.png",
    "qty": 1
    },
    {
    "id": "5",
    "head1": "Blowdry and Styling",
    "head2": "Blowdry: In Curl / Out Curl",
    "price": 399,
    "time": "45 mins",
    "des1": "Gives bouncy looking curls that last for a few hours",
    "desc2": "For a frizz-free, longer lasting look, please choose tong curls",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1650710728185-13cb5e.jpeg",
    "qty": 1
    },
    {
    "id": "6",
    "head1": "Blowdry and Styling",
    "head2": "Straightening",
    "price": 499,
    "time": "30 mins",
    "des1": "Longer lasting sleek, smooth and straighter hair",
    "desc2": "High-end professional straightener used to flat iron sections of hair",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1650712577621-7ce491.jpeg",
    "qty": 1
    },
    {
    "id": "7",
    "head1": "Blowdry and Styling",
    "head2": "Curls & Waves",
    "price": 499,
    "time": "30 mins",
    "des1": "Defined, thick, bouncy curls that last longer",
    "desc2": "Curling done using high-end professional tongs",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1650712585125-72cb41.jpeg",
    "qty": 1
    },
    {
    "id": "8",
    "head1": "Blowdry and Styling",
    "head2": "Wedding Ready Group Styling Package",
    "price": 1199,
    "time": "3 options",
    "des1": "Package of at least 3 styling services",
    "desc2": "Get each service at 399/-",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1650635192529-1c7ebd.jpeg",
    "qty": 1
    },
    {
    "id": "9",
    "head1": "COLOR TO BE PROVIDED",
    "head2": "Roots: Only Application",
    "price": 349,
    "time": "30 mins",
    "des1": "Up to 4 inches of grey coverage from roots",
    "desc2": "For perfect hair color results, healthier & stronger roots",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1637646873120-9c2c72.png",
    "qty": 1
    },
    {
    "id": "10",
    "head1": "STYLIST CARRIES COLOR",
    "head2": "Roots: Color & Application",
    "price": 849,
    "time": "4 options",
    "des1": "Up to 4 inches of grey coverage from roots",
    "desc2": "For perfect hair color results, healthier & stronger roots",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1639397627725-b8ee0b.png",
    "qty": 1
    },
    {
    "id": "11",
    "head1": "PACKAGE",
    "head2": "L'oreal Full Coverage: Color & Application",
    "price": 2449,
    "time": "45 mins",
    "des1": "Add",
    "desc2": "Shoulder Length",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1639397627725-b8ee0b.png",
    "qty": 1
    },
    {
    "id": "12",
    "head1": "Spa & Massage",
    "head2": "L'Oreal Nourishing Hair Spa",
    "price": 1349,
    "time": "1 option",
    "des1": "Curated 6 step rich repairing cream bath to strenghthen damaged hair",
    "desc2": "Provides maximum nourishment, for gorgeous bouncy hair",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1639396832039-ac31ba.png",
    "qty": 1
    },
    {
    "id": "13",
    "head1": "Spa & Massage",
    "head2": "Relaxing Head Oil Massage",
    "price": 349,
    "time": "25 mins",
    "des1": "A rejuvenating head massage for self-pampering sessions",
    "desc2": "Calming & relaxing therapy to boost hair growth, reduce hair fall",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1639397192787-73f069.png",
    "qty": 1
    },
    {
    "id": "14",
    "head1": "INCLUDES HAIR MASQUE",
    "head2": "L' Or�al Global Fashion Color - Signature reflects",
    "price": 2499,
    "time": "3 options",
    "des1": "Stylish and sophisticated hair colors",
    "desc2": "Stay on trend and flaunt gorgeous looking hair anytime and anywhere",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1651736991598-9e25ad.png",
    "qty": 1
    },
    {
    "id": "15",
    "head1": "INCLUDES BLOW-DRY",
    "head2": "L' Or�al Signature Highlights/Streaks",
    "price": 3149,
    "time": "3 options",
    "des1": "Add a different hue to your hair without an all-over commitment",
    "desc2": "Enhance your look with 10 foils, choose from 3 colored streak shades",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1639398010862-53633e.png",
    "qty": 1
    },
    {
    "id": "16",
    "head1": "INCLUDES BLOW-DRY",
    "head2": "Balayage/Ombre",
    "price": 3449,
    "time": "3 options",
    "des1": "Get soft, subtle & gradual color transitions across your hair",
    "desc2": "Choose from 3 light colored streak shades",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1639398073123-02f47c.png",
    "qty": 1
    },
    {
    "id": "17",
    "head1": "LONG LASTING RESULTS",
    "head2": "Keratin Treatment",
    "price": 3749,
    "time": "3 options",
    "des1": "Get soft & supple hair with this intensive moisture repair treatment",
    "desc2": "Reconstructs & strengthens damaged tips to eliminate frizz.",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1651736989968-06cbe1.png",
    "qty": 1
    },
    {
    "id": "18",
    "head1": "Party Essentials",
    "head2": "Blowdry: Straight & Smooth",
    "price": 399,
    "time": "30 mins",
    "des1": "Simple blowdry to give you smooth and straight hair for a few hours",
    "desc2": "For a frizz-free, longer lasting look, please choose straightening",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1651666584674-3b0b6c.png",
    "qty": 1
    },
    {
    "id": "19",
    "head1": "Party Essentials",
    "head2": "Blowdry: In Curl / Out Curl",
    "price": 399,
    "time": "45 mins",
    "des1": "Gives bouncy looking curls that last for a few hours",
    "desc2": "For a frizz-free, longer lasting look, please choose tong curls",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1650710728185-13cb5e.jpeg",
    "qty": 1
    },
    {
    "id": "20",
    "head1": "Party Essentials",
    "head2": "Straightening",
    "price": 499,
    "time": "30 mins",
    "des1": "Longer lasting sleek, smooth and straighter hair",
    "desc2": "High-end professional straightener used to flat iron sections of hair",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1650712577621-7ce491.jpeg",
    "qty": 1
    },
    {
    "id": "21",
    "head1": "Party Essentials",
    "head2": "Curls & Waves",
    "price": 499,
    "time": "30 mins",
    "des1": "Defined, thick, bouncy curls that last longer",
    "desc2": "Curling done using high-end professional tongs",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1650712585125-72cb41.jpeg",
    "qty": 1
    },
    {
    "id": "22",
    "head1": "COLOR TO BE PROVIDED",
    "head2": "Roots: Only Application",
    "price": 349,
    "time": "30 mins",
    "des1": "Up to 4 inches of grey coverage from roots",
    "desc2": "For perfect hair color results, healthier & stronger roots",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1637646873120-9c2c72.png",
    "qty": 1
    },
    {
    "id": "23",
    "head1": "STYLIST CARRIES COLOR",
    "head2": "Roots: Color & Application",
    "price": 849,
    "time": "4 options",
    "des1": "Up to 4 inches of grey coverage from roots",
    "desc2": "For perfect hair color results, healthier & stronger roots",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1639397627725-b8ee0b.png",
    "qty": 1
    },
    {
    "id": "24",
    "head1": "EXCLUDES HAIR WASH",
    "head2": "30 Minute Express Trim",
    "price": 549,
    "time": "35 mins",
    "des1": "A quick trim to remove split ends while minimally reducing hair length",
    "desc2": "Blowdry not included",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1650711648402-3502ab.jpeg",
    "qty": 1
    },
    {
    "id": "25",
    "head1": "Hair Care Essentials",
    "head2": "L'Oreal Nourishing Hair Spa",
    "price":1349,
    "time": "1 option",
    "des1": "Curated 6 step rich repairing cream bath to strenghthen damaged hair",
    "desc2": "Provides maximum nourishment, for gorgeous bouncy hair",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1639396832039-ac31ba.png",
    "qty": 1
    },
    {
    "id": "26",
    "head1": "Hair Care Essentials",
    "head2": "Relaxing Head Oil Massage",
    "price": 349,
    "time": "25 mins",
    "des1": "A rejuvenating head massage for self-pampering sessions",
    "desc2": "Calming & relaxing therapy to boost hair growth, reduce hair fall",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1639397192787-73f069.png",
    "qty": 1
    },
    {
    "id": "27",
    "head1": "LONG LASTING RESULTS",
    "head2": "Keratin Treatment",
    "price": 3749,
    "time": "3 options",
    "des1": "Get soft & supple hair with this intensive moisture repair treatment",
    "desc2": "Reconstructs & strengthens damaged tips to eliminate frizz.",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1651736989968-06cbe1.png",
    "qty": 1
    },
    {
    "id": "28",
    "head1": "EXCLUDES HAIR WASH",
    "head2": "30 Minute Express Trim",
    "price": 549,
    "time": "35 mins",
    "des1": "A quick trim to remove split ends while minimally reducing hair length",
    "desc2": "Blowdry not included",
    "images": "https://res.cloudinary.com/urbanclap/image/upload/t_high_res_template,q_auto:low,f_auto/images/growth/luminosity/1650711648402-3502ab.jpeg",
    "qty": 1
    }
    ]